version: "2.0"
services:
    mariadb:
        image: mariadb:10.2
        container_name: wesic-mariadb
        environment:
         - MYSQL_ROOT_PASSWORD=mypass
        volumes:
          - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    php:
        build:
          context: ./
          dockerfile: Dockerfile
        volumes:
          - ./src:/var/www/html/
        links:
         - mariadb:db
        ports:
          - "8080:80"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: wesic-phpmyadmin
        environment:
         - MYSQL_ROOT_PASSWORD=mypass
        ports:
         - "8082:80"
        links:
         - mariadb:db
